eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://discovery-server:8761/eureka}

server:
  port: 8060
spring:
  application:
    name: assurancePolicy
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST:devops-microservice-postgres-1}:${POSTGRES_PORT:5432}/${POSTGRES_DB:assurance}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL:http://zipkin:9411/api/v2/spans}